#cloud-config

# set hostname
hostname: jenkins

# update repos
repo_update: true
repo_upgrade: all

# update packages
package_upgrade: true

# install packages
packages:
  - git
  - curl
  - wget
  - default-jre
  - default-jdk

# run commands
runcmd:
  
  - curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  - echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - sudo ufw allow 8080
  - sudo apt update -y
  - sudo apt install jenkins -y
  - sudo systemctl start jenkins.service
  - sudo systemctl enable jenkins.service